import type { Metadata } from "next";
import { Archivo, Schibsted_Grotesk } from "next/font/google";
import "./globals.css";

// Display face (DESIGN.md § Typography): Archivo with its variable `wdth` axis
// requested explicitly — without `axes: ["wdth"]` the font ships at normal width
// and the width-contrast hierarchy disappears. The expanded rendering
// (font-stretch: 125%) is applied in globals.css.
//
// `fallback` is deliberately omitted on both faces. With it omitted, THIS
// build has next/font emit its own metric-adjusted fallback faces
// ("Archivo Fallback", "Schibsted Grotesk Fallback" — local Arial with
// ascent/descent/line-gap overrides and Next's precalculated size-adjust)
// and sets each CSS variable to the real family immediately followed by that
// adjusted face (verified in the production CSS: --font-schibsted resolves to
// "Schibsted Grotesk", "Schibsted Grotesk Fallback"). Passing `fallback: [...]`
// would instead bake generic families into the variable and push the adjusted
// face behind `sans-serif`, where it is unreachable — a generic always
// matches, so anything after it is dead.
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  axes: ["wdth"],
});

// Body face: Schibsted Grotesk. The spec table depends on its tabular figures
// (`tnum`) — verified working at the binary level on the served woff2 (all ten
// tabular digits at one advance width, spread 0; see .pact/tasks/f1-tokens-evidence/).
const schibstedGrotesk = Schibsted_Grotesk({
  variable: "--font-schibsted",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${archivo.variable} ${schibstedGrotesk.variable}`}>
      <body>{children}</body>
    </html>
  );
}
