import type { Metadata } from "next";
import { Archivo, Golos_Text } from "next/font/google";
import "./globals.css";

// Display face (DESIGN.md § Typography): Archivo with its variable `wdth` axis
// requested explicitly — without `axes: ["wdth"]` the font ships at normal width
// and the width-contrast hierarchy disappears. The expanded rendering
// (font-stretch: 125%) is applied in globals.css. `adjustFontFallback` is on by
// default, emitting size-adjust/ascent-override metrics on the fallback face.
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  axes: ["wdth"],
  fallback: ["Archivo", "Helvetica Neue", "sans-serif"],
});

// Body face: Golos Text. The spec table depends on its tabular figures (`tnum`).
const golosText = Golos_Text({
  variable: "--font-golos",
  subsets: ["latin"],
  fallback: ["Helvetica Neue", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${golosText.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
